### PR TITLE
new @Input "pixelSize" width in px

### PR DESCRIPTION
**Pull request by mrothauer**
i was missing an option for setting a fixed pixel width to an area.

* if there are e.g. three areas and one of them has [pixelSize] set to e.g. 500, the remaining space is used for the percentage based areas. 
* eg. [pixelSize]="500" sets the width for the area to 500px
* resizing the areas also works

maybe you can somehow integrate my code?

### CODE REVIEW

**Comment by jacobbutton** [comment]
Did this ever get merged? I really need a static pixel width for one of the panes but can't get this to work.

**Comment by mrothauer** [comment]
unfortunately not - my pull request remains open since may 2017.

**Comment by jacobbutton** [comment]
That's not very reassuring.

@bertrandg, any chance we can get this implemented?

**Comment by jacobbutton** [comment]
@bertrandg I think it's awesome you've reopened the project and that you're committed to including fixed pixel widths as a feature.  Do you have a timeline on that? Do you need any help in making it happen?

**Comment by bertrandg** [comment]
Version `2.0.0` will be released soon (one week max), it solves several bugs, and allow more flexibility about styles.

Then I will work on split area size options asked, I listed them:
* Min & max sizes percent/pixel (#4 & #82)
* Express sizes in pixel (#101)
* Lock area size (#97)
* Add wildcard size (#55)
* Move gutter around steps

First I will find what can be done to allow more asked scenarios possible and then start coding it.
So thanks for you proposition but not best time for it unless you already have a working solution allowing all options.
And no, I don't have more info about when feature will be added.

I keeped this PR opened because it's an interesting way to have fixed pixel area size but it will not be merged due to lots of changes inside repository.

**Comment by mrothauer** [comment]
I'm happy if my code helps in any way and that the project continues. If you can't merge my PR it's no problem for me.
Good luck!

**Comment by bertrandg** [comment]
Thanks @mrothauer, glad you said this, even if not merged it will help! ;)

**Pull request closed without merging**
