### PR TITLE
Visibility feature only

### PR DESCRIPTION
**Pull request by jitsmaster**
This pull request include only the visibility feature. The animate and layoutEnd features will be included in next pull request

### CODE REVIEW

**Comment by bertrandg** [comment]
Cool thanks.

Just discovered an other bug to fix:
bug_event_sizes

**Comment by jitsmaster** [comment]
The visibility for end areas fix just checked in. Could you give me a description of the new bug?

**Comment by bertrandg** [comment]
`dragStart`, `dragProgress` & `dragEnd` should send an array containing ordered visible areas percentage size (all values additionned equal 100).

Here areaA is not visible but value sended.

**Comment by jitsmaster** [comment]
Got it. Working on this

**Comment by bertrandg** [comment]
cool :)

**Comment by jitsmaster** [comment]
Done

**Comment by jitsmaster** [comment]
Thank you Sir.
I will look into the shadow dom issue for split component css. Then create second pull request

**Comment by bertrandg** [comment]
:)
I'm gonna publish 0.1.17 on NPM tonight and add it to website.

**Comment by jitsmaster** [comment]
Thank you

**Comment by Jefiozie** [comment]
@all-contributors please add @jitsmaster for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙

**Pull request merged**
